module.exports = require('./src/quickLoader')

require('./src/types/JSONPItem')
require('./src/types/JSONItem')
require('./src/types/TextItem')
require('./src/types/AudioItem')
require('./src/types/VideoItem')
require('./src/types/AnyItem')
require('./src/types/ImageItem')
require('./src/types/XHRItem')
